version: "3.5"
services:

  jobmanager:
    image: flink:1.14.2
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        web.log.path: /opt/flink/log/flink.log
    volumes:
      - "./log4j-console.properties:/opt/flink/conf/log4j-console.properties"

  taskmanager:
    image: flink:1.14.2
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        web.log.path: /opt/flink/log/flink.log
    volumes:
      - "./log4j-console.properties:/opt/flink/conf/log4j-console.properties"
